name: Test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from Moonfin repository'
        required: true
        default: 'main'

permissions:
  contents: write

jobs:
  # ───────────────────────────────────────────────
  # webOS IPK
  # ───────────────────────────────────────────────
  build-webos:
    name: Build webOS
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Litefin repository
        uses: actions/checkout@v6
        with:
          repository: 'Moonfin-Client/Smart-TV'
          ref: ${{ github.event.inputs.branch }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci --force

      - name: Build webOS
        id: build
        run: npm run build:webos

      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: webos
          path: |
            Moonfin_webOS_*.ipk
            packages/build-webos/org.moonfin.webos.manifest.json  
